---
abstract: 'Compare various array/set handling modules'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmark-Featureset-SetOps
provides:
  Benchmark::Featureset::SetOps:
    file: lib/Benchmark/Featureset/SetOps.pm
    version: 1.01
  Benchmark::Featureset::SetOps::Config:
    file: lib/Benchmark/Featureset/SetOps/Config.pm
    version: 1.01
requires:
  App::moduleswhere: 0.03
  Config::Tiny: 2.13
  Module::Version: 0.12
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.01
